version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Development_
    ports:
      - 1433:1433
    volumes:
      - db_data:/var/opt/mssql

volumes:
  db_data: